// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type CreatePostArgs = {
  readonly "text": string;
};

export type CreatePostReturns = {
  "id": string;
};

export function createPost(client: Executor, args: CreatePostArgs): Promise<CreatePostReturns> {
  return client.queryRequiredSingle(`\
insert Post {
    text := <str>$text,
    author := global current_user,
}`, args);

}
